### PR TITLE
Fix python3.8 not found issue at build env

### PR DESCRIPTION
**Pull request by k-hasan-19**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cakepietoast** [comment]
Thanks for the PR! This shouldn't be necessary if you follow the [steps in the README](https://github.com/aws-samples/aws-serverless-shopping-cart#option-2---automatically-deploy-backend-and-frontend-using-amplify-console) for creating the Amplify application though. Amplify is configured via an env var to use a custom build image which already includes python3.8 (its a bit hidden, see [here](https://github.com/aws-samples/aws-serverless-shopping-cart/blob/master/amplify-ci/amplify-template.yaml#L143)). This avoids the extra time it would take to build python3.8 from source for each build.

Let me know the steps you're taking if you're running into issues here, maybe I need to improve the docs.

**Comment by k-hasan-19** [comment]
Hey @cakepietoast , thanks for getting back on this. I was trying to deploy it directly from github using Amplify console and faced this `python3.8 not found` issue. Needed a quick fix and updated the build spec like that. I think others will try to deploy this app using console by few clicks like me and will face the same issue. Thus sent the quick PR.

**Comment by cakepietoast** [comment]
Makes sense, I'm reluctant to merge this as-is due to the impact on time to build for those who are using a custom build image that already includes python3.8. With that said, there are definitely improvements we could make here! Would you be willing to alter this PR to perform the steps _only on the condition that python3.8 isn't already installed_? Perhaps by supplying the installation steps as a shell script and conditionally calling with something like: `which python3.8 || ./install_python_3.8.sh`

I'd be happy to merge that, then I can update the README to provide a simplified deploy-with-amplify instruction (hopefully as simple as adding a [one click deploy button](https://docs.aws.amazon.com/amplify/latest/userguide/one-click.html), with an optional extra step to supply a custom image (e.g. one that already has python3.8 installed).

**Comment by swaminator** [comment]
@k-hasan-19 Amplify PM here. We are currently updating the build container to use Python 3.8 by default.

**Comment by cakepietoast** [comment]
> @k-hasan-19 Amplify PM here. We are currently updating the build container to use Python 3.8 by default.

Thanks @swaminator, thats great news. @k-hasan-19 I'll close this and make some improvements to simplify deploying with Amplify. Thanks for the inspiration!

**Comment by k-hasan-19** [comment]
Awesome!

**Pull request closed without merging**
